# Generated by Django 3.2 on 2023-02-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('following', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followingup',
            options={'ordering': ('-created',), 'verbose_name': 'Follow Up', 'verbose_name_plural': 'Follow Ups'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='followingup',
            old_name='score',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='followingup',
            old_name='note',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='station',
            new_name='center',
        ),
        migrations.AddField(
            model_name='followingup',
            name='lesson',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='followingup',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
